### PR TITLE
mrc-5428 add dev-start script

### PR DESCRIPTION
**Pull request by M-Kusumgar**
The aim of this was just to streamline setup for packit, felt like it could've just been one command so that is what I have done here

### CODE REVIEW

**Review by absternator — APPROVED** [review]
legend lgtm

**Review by EmmaLRussell — APPROVED** [review]
This is cool - I guess this is going to be most useful when you're revieiwing, or when working on the front end, as it isn't very conducive to tearing down and rerunning the backend container. But if you were doing that you'd probably just be running the backend with gradle anyway.

**Review by EmmaLRussell — COMMENTED** [review]
Might also be nice to include the auth method as as option!

**Comment by M-Kusumgar** [comment]
> Might also be nice to include the auth method as as option!

will add this in this ticket: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-5435/Add-auth-method-in-dev-start-script mainly because im not actually sure what possible values for the auth methods there are and also if i have to change anything other than the auth in the app properties

**Pull request merged**
