### PR TITLE
Mrc 3979 Add linting to front-end app

### PR DESCRIPTION
**Pull request by LekanAnni**
PR adds esLint to frontend with typescript support. 

Ticket based off mrc-3978

### CODE REVIEW

**Comment by hillalex** [comment]
Merged the other PR, so if you get this up to date with main I will review this next :)

**Comment by LekanAnni** [comment]
> Merged the other PR, so if you get this up to date with main I will review this next :)

Merged

**Review by hillalex — CHANGES_REQUESTED** [review]
Nice, looking really tidy!

**Review by hillalex — APPROVED** [review]
Oops, meant to approve

**Pull request merged**
